### ISSUE TITLE
runabove просто так отбирает серверы

### ISSUE THREAD

**Issue by alice2k** [runabove/metronome#35]
runabove просто так отбирает серверы
которые были оплачены до апреля 2017 года
плюс мне пришлось купить 4 новых сервера, а оказалось что я не могу забрать свои сети IP которые купил ранее на RBX-HZ 

итого я просрал кучу денег ! 
я хотел продлять серверы, но они тупо их отключили
https://hostsuki.pro/all/runabove-ne-stoit-zakazyvat-v-principe.html
и даже возвратов не сделали 
потерял много денег 

http://se1.yapcdn.net/1/8yZ0dr.png
http://se2.yapcdn.net/1/nDZegiBjhcDoDY6m.png
https://se3.yapcdn.net/1/lxNekjHia.png
https://se3.yapcdn.net/1/lxNekjHia.png

**Comment by d33d33** [comment]
@alice2k Sorry for that, this is an open source project so we are not providing support fot runabove offers. Feel free to contact them trough https://cloud.runabove.com/#/support
