### ISSUE TITLE
runabove отбирает работающие сервера и не делает возвратов 

### ISSUE THREAD

**Issue by alice2k** [runabove/metronome#36]
runabove отбирает работающие сервера и не делает возвратов 
2 сервера 16+16+16+16+64 сетей 
сколько бабла ушло 
и еще 4 новых сервера в пустую купил, а сети не переносятся! 
и я был готов продлять и по 90 евро даже. я зачем покупал ? чтобы пользоваться. 
https://eu.soyoustart.com/manager/?csid=NaPKd#/support/messages/4579531
https://eu.soyoustart.com/manager/?csid=NaPKd#/support/messages/4660779

**Comment by d33d33** [comment]
@alice2k Sorry for that, this is an open source project so we are not providing support fot runabove offers. Feel free to contact them trough https://cloud.runabove.com/#/support
